### ISSUE TITLE
KubernetesProvisioner.pre_launch throw key error when launch kernel

### ISSUE THREAD

**Issue by BetterLevi** [jupyter-server/gateway_provisioners#125]
## Search similar
I've searched existed issues and not found similar one
## Description
I'm using Nbconvert to execute a ipnb file to notebook, the kernel is k8s_python, when I execute the command `jupyter nbconvert --to notebook --execute Untitled.ipynb`, it will throw error:
```
[NbConvertApp] Instantiating kernel 'Kubernetes Python' with kernel provisioner: kubernetes-provisioner
[NbConvertApp] ResponseManager is bound to port 8877 for remote kernel connection information.
[NbConvertApp] ERROR | 'env'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_client/manager.py", line 436, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_client/manager.py", line 401, in _async_pre_start_kernel
    kw = await self.provisioner.pre_launch(**kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/gateway_provisioners/k8s.py", line 88, in pre_launch
    kwargs["env"][key] = os.environ[key]
    ~~~~~~^^^^^^^
KeyError: 'env'
```
### Reproduce
1. execute command `jupyter nbconvert --to notebook --execute Untitled.ipynb`
2. Untitled.ipynb content is:
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb001297-d64e-474a-8665-02c3f8388a6c",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(1)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Kubernetes Python",
   "language": "python",
   "name": "k8s_python"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

```

## Expected behavior
I checked this method and found one line was removed in the commit `4c82a80 `, and this may lead this error occurs,  not sure delete it for what reason.
![image](https://github.com/jupyter-server/gateway_provisioners/assets/26360198/67ee5eb2-559e-4cd7-9640-8813b08e4505)

**Comment by kevin-bates** [comment]
Hi @BetterLevi - thank you for bringing this to our attention.  Yes, this will be an issue when the `kwargs` does not already contain an `"env"` key.  I suppose one question is why is your `kwargs` missing that key as it is commonly used?

Nevertheless, this is a bug that needs to be fixed.  I would suggest adding:
```
kwargs["env"] = kwargs.get("env", {})
```
prior to the for loop to ensure the key's existence.

Are you able to provide a pull request to address this (after confirming your issue is resolved)?  It would be greatly appreciated.

**Comment by BetterLevi** [comment]
It's ok to fix `key error` by adding `kwargs["env"] = kwargs.get("env", {})` to the prior of the loop, but this may lead to `kwargs["env"]` lost some values, e.g `$PATH`. 
So my suggestion is adding:
```
kwargs["env"] = dict(os.environ, **kwargs.get("env", {}))
```
back. What do you think?

**Comment by kevin-bates** [comment]
hi @BetterLevi.  Thanks for looking into this and asking the question.  There is some history there.

This latest change derived from this [Enterprise Gateway PR](https://github.com/jupyter-server/enterprise_gateway/pull/1164).  Previously, we had included the complete **_EG process env_** so that the K8s-related variables could be included in the soon-to-be-launched kernel pod.

The `$PATH` reference you make is really the PATH env for the _launching process_ and may reflect the same within the container hosting the kernel (but you probably shouldn't assume the launching process's PATH has relativity in the POD image).

There are multiple ways to influence the kernel pod's PATH:
- Add a PATH entry to the kernel's `kernel.json` file using a [_templated env_](https://github.com/jupyter/jupyter_client/pull/472).
- Pass PATH in an env dictionary when starting the kernel via the API.
- Bake the appropriate PATH into the kernel image.

Is your use case one in which the kernel's need to use the same PATH as that of their launching server?

**Comment by BetterLevi** [comment]
Thanks @kevin-bates for the details and helpful advice.
In my case, launching server is using `conda` to manage python env, so python path is like `/opt/conda/bin`. If `kwargs["env"]` missing `path`, the _launching process_ will start fail because python env can not be found.
I understood what you mentioned, and I have another question, from my understanding, superclass call should be called first before using`kwargs` (just like `DockerProvisioner` and `DockerSwarmProvisioner` does), but why `KubernetesProvisioner.pre_launch` do the loop first?

**Comment by BetterLevi** [comment]
hi @kevin-bates may I get your answer to the question above?

**Comment by kevin-bates** [comment]
Hi @BetterLevi - I apologize for the delay and appreciate the extra ping - this had fallen off my radar (email display :smile:).

> And from my understanding, superclass call should be called first before usingkwargs (just like DockerProvisioner and DockerSwarmProvisioner does), but why KubernetesProvisioner.pre_launch do the loop first? Is it to avoid passing useless env values?

I agree that consistency is nice.  The reason for this particular deviation is [commented in the top line of the method](https://github.com/jupyter-server/gateway_provisioners/blob/14553109ff60a07dd6aef441c4ab781399092138/gateway_provisioners/k8s.py#L78) so that whatever envs are added will be logged via a debug message. This was probably done in Enterprise Gateway during development of the `KubernetesProcessProxy` and inherited here.

Since it would be good to see the "final" envs for all provisioners, I'm inclined to do the following:
1. Move the call to `super()` in `KubernetesProvisioner` to replace the previously mentioned comment.
2. Move the [debug statement](https://github.com/jupyter-server/gateway_provisioners/blob/14553109ff60a07dd6aef441c4ab781399092138/gateway_provisioners/remote_provisioner.py#L143) in `RemoteProvisionerBaae.pre_launch()` to `RemoteProvisionerBase.launch_kernel()` just [prior to its call to `gp_launch_kernel()`](https://github.com/jupyter-server/gateway_provisioners/blob/14553109ff60a07dd6aef441c4ab781399092138/gateway_provisioners/remote_provisioner.py#L149) (and after scrubbing the kwargs).
3. Since the `DistributedProvisioner` completely overrides `launch_kernel()` it would be good to dump the env just after it scrubs the kwargs [here](https://github.com/jupyter-server/gateway_provisioners/blob/14553109ff60a07dd6aef441c4ab781399092138/gateway_provisioners/distributed.py#L152) so that the DEBUG output will be consistent across provisioners.

Does this answer your question?  Would you like to include these changes in a pull request?

**Comment by ezemtsov** [comment]
Having the same issue, is there a workaround available?
If the issue is fixed, could we release a new version?

**Comment by BetterLevi** [comment]
hi @ezemtsov not sure can release a new version. my workaround is modify the source code and package locally.
